### ISSUE TITLE
login getting success but functions are not working .. error as bad request..

### ISSUE THREAD

**Issue by tradewithmadhan** [BennyThadikaran/Kite-Trader#3]
login getting success but functions are not working .. error as bad request.. request to please check ...

**Comment by BennyThadikaran** [comment]
See the update in the [README](https://github.com/BennyThadikaran/Kite-Trader?tab=readme-ov-file#update)

Due to changes in KITE api the web login is broken. The enctoken is no longer accepted for Kite Connect urls. You can still use the Kite Web url as workaround. But i dont support it here, since its a lot of work and subject to breaks in the future.

**Comment by BennyThadikaran** [comment]
I have just released v3.0.2 which allows downloading historical data and instruments. The rest of the methods will be unavailable on Kite Web. Run `pip install -U kitetrader` to update to the latest.
